title = 'PCL 群组服帮助文档'
description = '社区维护的 PCL 群组服帮助文档 兼 脑溢血治疗中心'
evergreen = true
'link' = { rel = 'icon', href = 'https://cdn.jsdelivr.net/gh/Big-Cake-jpg/Image_For_My_Blog/favicon.png' }

[locales]
'/' = { lang = 'zh-CN', title = 'PCL 群组服帮助文档' }

[themeConfig]
repo = 'Big-Cake-jpg/pcls-docs'
docsBranch = 'source'
docsDir = 'docs'
editLinks = true
smmothScrool = true

[themeConfig.locales.'/']
editLinkText = '帮助我们完善这个页面'
lastUpdated = '最后更新'

[[themeConfig.locales.'/'.nav]]
text = '主页'
link = '/'
[[themeConfig.locales.'/'.nav]]
text = '生存服'
link = '/main-server/'
[[themeConfig.locales.'/'.nav]]
text = '方块竞技场'
link = '/block-fight-server/'
[[themeConfig.locales.'/'.nav]]
text = '玩前必看'
link = '/before-playing/'

[themeConfig.locales.'/'.sidebar]
'/main-server/' = [
  '/main-server/how-to-play',
  '/main-server/notes',
]
'/block-fight-server/' = []

'/before-playing/' = [
  '/before-playing/system-requirements',
  '/before-playing/qq-group-rules',
  '/before-playing/server-rules',
]